
// Objective-C API for talking to the following Go packages
//
//	github.com/jerson/rsa-mobile/rsa
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Rsa_FRAMEWORK_H__
#define __Rsa_FRAMEWORK_H__

#include "Rsa.objc.h"
#include "Universe.objc.h"

#endif
