name: Hover

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@main
        with:
          flutter-version: '3.x'
          channel: 'stable'
      - uses: actions/setup-go@v3
      - run: GO111MODULE=on go get -u -a github.com/go-flutter-desktop/hover@latest
      - name: config
        run: |
          git config --local user.email "bot+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git remote remove origin || echo "skipped"
          git remote add origin "https://${{ secrets.TOKEN }}@github.com/${{ github.repository }}.git"
      - run: yes | `go env GOPATH`/bin/hover publish-plugin